# Generated by Django 6.0.3 on 2026-03-25 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_members', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Amount each non-winner pays per round', max_digits=10)),
                ('prize_amount', models.DecimalField(decimal_places=2, help_text='Total prize amount winner receives', max_digits=12)),
                ('frequency_months', models.PositiveIntegerField(choices=[(1, 'Monthly'), (2, 'Every 2 Months'), (3, 'Every 3 Months'), (6, 'Every 6 Months')], default=3, help_text='How often the chit auction happens')),
                ('total_rounds', models.PositiveIntegerField(help_text='Total number of rounds (equal to total members)')),
                ('start_date', models.DateField()),
                ('due_day', models.PositiveIntegerField(default=10, help_text='Day of month by which payment is due')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, help_text='Penalty for late payment', max_digits=8)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed')], default='upcoming', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chit Group',
                'verbose_name_plural': 'Chit Groups',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')])),
                ('alternate_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(help_text='Member slot number in this group')),
                ('has_won', models.BooleanField(default=False)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='management.chitgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='management.member')),
            ],
            options={
                'verbose_name': 'Chit Membership',
                'verbose_name_plural': 'Chit Memberships',
                'ordering': ['chit_group', 'slot_number'],
                'unique_together': {('chit_group', 'member'), ('chit_group', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='ChitRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('round_date', models.DateField()),
                ('winner_installment_amount', models.DecimalField(decimal_places=2, help_text='Reduced amount winner pays this round', max_digits=10)),
                ('others_installment_amount', models.DecimalField(decimal_places=2, help_text='Amount all other members pay', max_digits=10)),
                ('prize_amount', models.DecimalField(decimal_places=2, help_text='Prize disbursed to winner', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('disbursed_date', models.DateField(blank=True, null=True)),
                ('disbursement_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='management.chitgroup')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_rounds', to='management.chitmembership')),
            ],
            options={
                'verbose_name': 'Chit Round',
                'verbose_name_plural': 'Chit Rounds',
                'ordering': ['chit_group', 'round_number'],
                'unique_together': {('chit_group', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_winner_payment', models.BooleanField(default=False, help_text="True if this is the winner's discounted payment")),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('late', 'Late')], default='pending', max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('chit_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='management.chitround')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='management.chitmembership')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-chit_round__round_date'],
                'unique_together': {('membership', 'chit_round')},
            },
        ),
    ]
