# Generated by Django 6.0.3 on 2026-03-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('planned_date', models.DateField()),
                ('winner_installment_amount', models.DecimalField(decimal_places=2, help_text='Amount the winner of this round pays', max_digits=10)),
                ('others_installment_amount', models.DecimalField(decimal_places=2, help_text='Amount all other members pay (usually fixed)', max_digits=10)),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_schedules', to='management.chitgroup')),
            ],
            options={
                'verbose_name': 'Round Schedule',
                'verbose_name_plural': 'Round Schedules',
                'ordering': ['chit_group', 'round_number'],
                'unique_together': {('chit_group', 'round_number')},
            },
        ),
    ]
