# Generated by Django 6.0.3 on 2026-03-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_roundschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitround',
            name='others_installment_amount',
        ),
        migrations.RemoveField(
            model_name='chitround',
            name='prize_amount',
        ),
        migrations.RemoveField(
            model_name='chitround',
            name='winner_installment_amount',
        ),
    ]
