# Generated by Django 6.0.3 on 2026-03-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_chitround_others_installment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitround',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF or image', null=True, upload_to='round_documents/'),
        ),
    ]
