# Generated by Django 6.0.3 on 2026-03-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_chitround_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitround',
            name='surety_details',
            field=models.TextField(blank=True, help_text='Surety/guarantor details for this round', null=True),
        ),
    ]
