# Generated by Django 6.0.3 on 2026-03-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_chitround_surety_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
