# Generated by Django 6.0.3 on 2026-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitround',
            name='lift_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount given to the lift member this round', max_digits=12, null=True),
        ),
    ]
