# Generated by Django 6.0.3 on 2026-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_chitround_lift_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitmembership',
            name='committed_lift_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Committed lift amount for this member', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='chitmembership',
            name='committed_round_number',
            field=models.PositiveIntegerField(blank=True, help_text='Round number in which this member is committed to receive the lift amount', null=True),
        ),
    ]
